### ISSUE TITLE
Remove my code, or you get a DMCA Takedown Request

### ISSUE THREAD

**Issue by Sascha-T** [RootBotTeam/RootBot#19]
As i dont agree with the latest license, i demand my code to be removed, or i will file a Takedown Request

**Comment by DUFC-Liam** [comment]
You were hired on this to code for RootBot you were not hired as a freelancer to add code and remove it as you wish- under what legal ground should I remove the code.

**Comment by Sascha-T** [comment]
This license was not here before, therefore i will file a dmca takedown request
