### ISSUE TITLE
Suggestion: Block all commands for Ale32bit#5164

### ISSUE THREAD

**Issue by PrismaticYT** [RootBotTeam/RootBot#3]
Ale32bit#5164 made rude comments about RootBot, saying it is a 'stupid bot' and that the creator (Liam) should 'die in a hole'. Therefore, you should block commands for him.

**Comment by DUFC-Liam** [comment]
My apologies that what the user has said about the bot and me but I cannot global ban him at the moment but I will speak to the user and if they seem like they still hate us I will remove the bot from his server (if he is the owner)

**Comment by Sascha-T** [comment]
Mate im making global ban system now. Thanks for the suggestion lmao

**Comment by Sascha-T** [comment]
ok maybe not today or 23 days ago
